version: "3"

services:
  web:
    # image: stilleshan/dujiaoka
    build: .
    environment:
        - INSTALL=true
        # - INSTALL=true
        # - MODIFY=true

    volumes:
      - ../dujiao_volume/env.conf:/dujiaoka/.env
      - ../dujiao_volume/uploads:/dujiaoka/public/uploads
      - ../dujiao_volume/storage:/dujiaoka/storage
    ports:
      - 56789:80
    restart: always
 
  # db:
  #   image: mariadb:focal
  #   restart: always
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=YOUR_PASSWORD
  #     - MYSQL_DATABASE=dujiaoka
  #     - MYSQL_USER=dujiaoka
  #     - MYSQL_PASSWORD=YOUR_PASSWORD
  #   volumes:
  #     - ../dujiao_volume/mysql:/var/lib/mysql

  redis:
    image: redis:alpine
    restart: always
    volumes:
      - ../dujiao_volume/redis:/data
